### ISSUE TITLE
Is there supposed to be a DLL in this mod?

### ISSUE THREAD

**Issue by HebaruSan** [dogevspenguin/North-Kerbin-Dynamic-Renewed#1]
Hi, I'm reviewing this for addition to CKAN in KSP-CKAN/NetKAN#8054, and I had a question.

The original mod had a NorthKerbinMod.dll file that presumably played some role in enabling big explosions:

- ![image](https://user-images.githubusercontent.com/1559108/87882037-d0c11100-c9ec-11ea-9b57-eb93f8e96c3d.png)

The Renewed mod does not have this file. Is this intentional?

Tagging @dogevspenguin because GitHub is weird about notifications.

**Comment by dogevspenguin** [comment]
yes but the dll is not used and i can't uncompile it so there virtually no way i can uncompile it on my own

**Comment by HebaruSan** [comment]
OK, in that case, never mind!
